### ISSUE TITLE
Vitejs 3.0

### ISSUE THREAD

**Issue by dayofr** [nabla/vite-plugin-eslint#12]
Hi, thank you for this awesome plugin.

Do you plan to make it compatible with Vitejs 3 ?

Regards.

**Comment by reintroducing** [comment]
I just went to install Vite 3 in my project and also realized that the peerDependency is set to `^2` and thus causing issues with a 3+ install. Would be great to update the peer deps to support 3 if possible. I know I can override the npm install to force the update but I'd rather not.

**Comment by ArnaudBarre** [comment]
Yes I think the only thing to fix is the peerDependency range, I will publish a version later today

**Comment by ArnaudBarre** [comment]
Available in `1.4.1` 🎉

**Comment by reintroducing** [comment]
@ArnaudBarre Thank you for the quick turnaround on this, much appreciated!
