### ISSUE TITLE
What should I do to solve this problem?

### ISSUE THREAD

**Issue by smartyoon** [nabla/vite-plugin-eslint#15]
...........

**Comment by ArnaudBarre** [comment]
This plugin is `@nabla/vite-plugin-eslint` not `vite-plugin-eslint`.

You problem seems more related to an eslint configuration issue than the logger of those errors.

Also please provide a small scoped reproduction when submitting bugs: https://antfu.me/posts/why-reproductions-are-required

**Comment by smartyoon** [comment]
I'm sorry. I posted it wrong.
