### ISSUE TITLE
Log issues to the Vite overlay

### ISSUE THREAD

**Issue by elwynelwyn** [nabla/vite-plugin-eslint#2]
Hello,

Any plans or desire to support logging ESLint issues to the Vite overlay in-browser?

Cheers!

**Comment by ArnaudBarre** [comment]
Hello!

I don't plan to support this as I think a linter should not bother you when iterating and trying hacky things to see if it works. It should only be something that helps you produce good and standard production code.

For the same reason the default of the plugin is to use one line console logs, and all rules are set to warning in our config (but we use `--max-warnings 0` in CI)

**Comment by elwynelwyn** [comment]
Fair enough!
