### ISSUE TITLE
Add support for flat config (`eslint.config.js`)

### ISSUE THREAD

**Issue by rakleed** [nabla/vite-plugin-eslint#23]
Please add support for [flat config](https://eslint.org/docs/latest/use/configure/configuration-files-new) (`eslint.config.js`), which is fully supported since ESLint [8.2.23](https://github.com/eslint/eslint/releases/tag/v8.23.0). Since in [version 9 eslintrc support will be deprecated](https://eslint.org/blog/2023/10/flat-config-rollout-plans/), and in version 10 it will be completely removed. And now the following error appears in the console:
```log
ConfigurationNotFoundError: No ESLint configuration found in ...
```

**Comment by ArnaudBarre** [comment]
I will look into it before releasing a version this week to include Vite 5 as a peer dep, but I'm not sure the issue comes from the plugin, it only runs ESLint programmatically via a Vite hook.

**Comment by ArnaudBarre** [comment]
`FlatESLint` is still considered an unsupported api via the `use-at-your-own-risk` package export. 

The documentation is inexistante, `FlatESLint` is mentioned  only once on the [documentation page](https://eslint.org/docs/latest/use/configure/configuration-files-new#configuration-file), and otherwise only in blog posts.

The automatic switch is only done at the CLI level only, which makes author of tooling need to re-implement it.

I will not add this support until at least its marked as possible to option for tooling author building on top of ESLint (ping @nzakas just in case)

**Comment by nzakas** [comment]
It's definitely time to start supporting flat config:
https://eslint.org/blog/2023/10/flat-config-rollout-plans/
https://eslint.org/blog/2023/11/whats-coming-in-eslint-9.0.0/

We have a migration guide for plugins:
https://eslint.org/docs/latest/extend/plugin-migration-flat-config

**Comment by ArnaudBarre** [comment]
This tool is not a plugin, it runs ESLint in a worker and lint files when Vite notice an update.
And as far as I can tell there is no documentation on how tool running ESLint via the JS API are expected to support both use cases for users, expect reading the source code of the CLI and replicating changes, which means importing things "at my own risk".
I don't want to imports things like this, ship that to hundreds of developers and then have issues if you break the non-JS API.

Do I need to wait for an official v9 to import a stable version of FlatESLint constructor?

**Comment by nzakas** [comment]
Ah gotcha, thanks for clarifying. Hard to grasp context when I'm mentioned into a project I'm not familiar with.

> Do I need to wait for an official v9 to import a stable version of FlatESLint constructor?

No. It's safe to do this now. Basically, you'd want to do something like this:

```js
const { FlatESLint, LegacyESLint, shouldUseFlatConfig } = require("eslint/use-at-your-own-risk");

if (await shouldUseFlatConfig()) {
    // use FlatESLint
} else {
    // use LegacyESLint
}
```

This will work both in v8 and in v9 as detailed in the [blog post](https://eslint.org/blog/2023/10/flat-config-rollout-plans/). In v9, the `ESLint` class will be equivalent of `FlatESLint` now, so if you choose just to support flat config for ESLint v9 then you can just use the `ESLint` class after that point.

**Comment by ArnaudBarre** [comment]
Thanks for the update and clarify this is safe to use despite the export name. I will add support for this soon

**Comment by nzakas** [comment]
You're welcome. We chose the export name to make it clear that these are somewhat temporary APIs but definitely safe to use through v9.

**Comment by ArnaudBarre** [comment]
Available in [v2](https://github.com/nabla/vite-plugin-eslint/releases/tag/v2.0.2) 🎉

**Comment by rakleed** [comment]
@ArnaudBarre I get this error:

```log
> vite

✘ [ERROR] Missing "./src" specifier in "@nabla/vite-plugin-eslint" package [plugin externalize-deps]

    node_modules/esbuild/lib/main.js:1374:27:
      1374 │         let result = await callback({
           ╵                            ^

```

<details>
<summary>vite.config.js</summary>

```js
import react from '@vitejs/plugin-react';
import eslintPlugin from '@nabla/vite-plugin-eslint/src';

// https://vitejs.dev/config/
export default {
  plugins: [
    react(),
    eslintPlugin(),
  ],
  server: {
    open: true,
  },
};
```

</details>

Vite 5.0.0, @nabla/vite-plugin-eslint 2.0.0

**Comment by jurosh** [comment]
@ArnaudBarre Just migrated to Vite v5 and still having issue with plugin even on version `2.0.2`.

```
node:internal/event_target:1083
  process.nextTick(() => { throw err; });
                           ^
TypeError [Error]: shouldUseFlatConfig is not a function
    at Object.<anonymous> (/PROJECT/node_modules/@nabla/vite-plugin-eslint/src/worker.cjs:12:21
   ...
```

I suppose error is related to this issue ?

**Comment by ArnaudBarre** [comment]
Probably running an oudated version of ESLint, I will bump the peer dep range in a next patch (added in 8.41 it seems)

**Comment by jurosh** [comment]
> Probably running an oudated version of ESLint, I will bump the peer dep range in a next patch (added in 8.41 it seems)

Yea this is it! Upgrading to `eslint@8.54.0` resolved issue. :+1:
And yep looks like it is `8.41` https://eslint.org/blog/2023/05/eslint-v8.41.0-released/
