### ISSUE TITLE
TypeError [Error]: LegacyESLint is not a constructor

### ISSUE THREAD

**Issue by wmonecke** [nabla/vite-plugin-eslint#29]
I am seeing the following error when running this plugin.

Any ideas on how to approach this?

Thank you!

**Comment by ArnaudBarre** [comment]
Hum yeah this probably because you're running a version of ESLint before 8.43 something. I should bump the peer deps range

**Comment by wmonecke** [comment]
Ah I see, ill update, thank you!

**Comment by ArnaudBarre** [comment]
Fixed on [2.0.4](https://github.com/nabla/vite-plugin-eslint/releases/tag/v2.0.4)!
