### ISSUE TITLE
Required package: debug

### ISSUE THREAD

**Issue by zakaoai** [nabla/vite-plugin-eslint#32]
Hello, I'm trying to handle flatconfig and I tested this fork but got the following error : 
`error when starting dev server:
Error: @nabla/vite-plugin-eslint tried to access debug, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.`

Using Yarn PnP 4.1.1

**Comment by ArnaudBarre** [comment]
Fixed on [2.0.4](https://github.com/nabla/vite-plugin-eslint/releases/tag/v2.0.4)!
