### ISSUE TITLE
Installation warnings when using with eslint v9

### ISSUE THREAD

**Issue by jurosh** [nabla/vite-plugin-eslint#33]
Error:
```
➤ YN0060: │ eslint is listed by your project with version 9.5.0 (pc01ad), which doesn't satisfy what @nabla/vite-plugin-eslint and other dependencies request (^8.56.0).
```

Looks like it is compatible, just need to bump dependencies

**Comment by jurosh** [comment]
Weird, I see that it's listed as ` "eslint": "^8.45 || ^9"` so should be OK... But for some reason Yarn is not happy

**Comment by ArnaudBarre** [comment]
Are you using the latest version and not an older one?

**Comment by jurosh** [comment]
I think it's the second part which is important `and other dependencies request`
- looks like I have plenty more deps which are not yet compatible with eslint v9, so could be that this error is not at all real problem with vite-plugin-eslint but some other deps

Closing this...
