### ISSUE TITLE
Vite dev server not loading because of require syntax

### ISSUE THREAD

**Issue by miachenmtl** [nabla/vite-plugin-eslint#5]
After updating to vite 2.6.14, the dev server fails on load with this error message:
```
Error [ERR_REQUIRE_ESM]: require() of ES Module ........../node_modules/chalk/source/index.js from .........../node_modules/@nabla/vite-plugin-eslint/worker.js not supported.
```
I tried replacing this plugin with the original vite-plugin-eslint@1.0.3, which uses import statements instead of require, and that works fine.

Edit: See https://github.com/vitejs/vite/issues/5694

**Comment by ArnaudBarre** [comment]
It's due to chalk 5 using ESM. It was a bad idea to use a wildcard for the versioning of it. I pinned it to v4 in 1.3.5
