### ISSUE TITLE
Default Regex Issue (Vue3/TS)

### ISSUE THREAD

**Issue by invokermain** [nabla/vite-plugin-eslint#7]
Hi, thanks for making this plugin, it's very simple but good.

Just in case anyone else has this issue...

In my project, the paths come through as `src/frontend/src/App.vue` (notice the lack of a leading / character), no idea why. Therfore it seemed the plugin was not doing anything because none of the paths matched. The shouldLint regex had to be amended to `/\/?src\/[^?]*\.(vue|m?[jt]sx?)$/.test(path)` and now it works fine.

One thing is that I could only really debug this by setting `shouldLint: () => true` to see what paths it was passing to the regex check. Maybe it's worth adding a --debug option? e.g. 'x' has changed but not matched regex so ignored. Just food for thought. I wish my understanding of vite was better and I could say why the paths came through differently in my project.

**Comment by ArnaudBarre** [comment]
Hi, thanks for the idea. There is already a debug option in vite, so it should not be very hard.

I don't use Vue so I don't know how Vite handles virtual files, but if you want a better understanding of how vite works, you. can add this little plugin to log requests:
```ts
    {
      name: "log",
      enforce: "pre",
      load(id) {
        console.log("resolve", id);
        return null;
      },
      transform(code, id) {
        console.log("transform", id, code);
        return null;
      }
    },
```

or use https://github.com/antfu/vite-plugin-inspect
