### ISSUE TITLE
How to intercept normal execution of program in case of eslint error

### ISSUE THREAD

**Issue by vijay19920608** [nabla/vite-plugin-eslint#8]
I need to display the eslint error message on the page when eslint reports an error

**Comment by ArnaudBarre** [comment]
Hello,

As explained [here](https://github.com/nabla/vite-plugin-eslint/issues/2#issuecomment-932065984) this is not in the scope of this plugin. 

You can try [vite-plugin-checker](https://github.com/fi3ework/vite-plugin-checker) or less popular but more scoped [vite-plugin-eslint-logger](https://github.com/Joker/vite-plugin-eslint-logger)
