### ISSUE TITLE
Error  Unexpected token '.'

### ISSUE THREAD

**Issue by jewe11er** [nabla/vite-plugin-eslint#9]
Got a error:

node_modules/@nabla/vite-plugin-eslint/src/worker.js:37
      if (e.messageTemplate === "file-not-found" && e.messageData?.pattern) {

**Comment by ArnaudBarre** [comment]
What version of node are you running?

**Comment by ArnaudBarre** [comment]
You're probably running node 12, which it's support is ending in 2 weeks, so I'm closing it as a won't fix
